SELECT ID_NUM_PROV_NVO, NOM_COMERCIAL_NVO, FOLIOCONVENIO, VERSION, DESC_TIPOCONV_,  ID_NUM_CONV, ID_NUM_VER, ID_NUM_PLAZOPAGO
FROM SORIANA_PROJECTS.dbo.[F_CONVENIOS_LEGADO_CITY](?)
WHERE
    UPPER([DESC_TIPOCONV_]) LIKE '%ESCALA%';